### ISSUE TITLE
Allow more than 1 style of custom model per attraction

### ISSUE THREAD

**Issue by ItzSkyy** [TheClowner/ccRides-Support#48] opened 2022-10-01 16:36 UTC
Example, teacups, ferris wheel, jets. if you see these IRL they usually consist of multiple designs instead of just only 1 design.    which would give the rides a bit more aesthetically pleasing look instead of all just 1 color/model

**Comment by TheClowner** [comment] 2022-10-03 18:27
This is a duplicate of https://github.com/TheClowner/ccRides-Support/issues/39 - which is already planned.

**Closed as completed** 2022-10-03 18:27 UTC
Labels: duplicate, Feature Request
