### ISSUE TITLE
SmoothCoasters comptability

### ISSUE THREAD

**Issue by PanetiX** [TheClowner/ccRides-Support#42] opened 2022-01-06 13:27 UTC
Hello,
would be great that ccRides will be compatible with SmoothCoasters Mod :)
https://www.curseforge.com/minecraft/mc-mods/smoothcoasters

This will significantly improve the experience of players when they are on a ride.

**Comment by PanetiX** [comment] 2022-05-05 09:23
Hey, any updates for this? Here is an API for this ... 
https://github.com/56738/SmoothCoastersAPI

**Comment by TheClowner** [comment] 2022-06-16 10:46
This is a duplicate of https://github.com/TheClowner/ccRides-Support/issues/24

**Closed as completed by TheClowner** 2022-06-16 10:46 UTC
Labels: Feature Request
