### ISSUE TITLE
API Support

### ISSUE THREAD

**Issue by derech1e** [TheClowner/ccRides-Support#28] opened 2021-03-09 18:20 UTC
**Describe the feature you'd like with as much detail as possible**
Is there any type of API in the Plugin? It would be great if an API could be implemented. I really need an interface to this Plugin!

Thank you! ;D

**Comment by TheClowner** [comment] 2021-03-10 07:19
Duplicate of #19 
An API is planned for the future already.

**Closed as completed by TheClowner** 2021-03-10 07:19 UTC
Labels: duplicate, Feature Request
